GET http://localhost:3000/api/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjQxODYxZmZmY2M0NjY0MWIyNjFkYjMiLCJpYXQiOjE3MTU2NTcyOTAsImV4cGlyZXMiOiIyMDI0LTA1LTE0VDAzOjI5OjEwLjc0MVoiLCJ0eXBlIjoiYWNjZXNzIn0.ShhsRbflRp8tRWyXuCT_tBHvv9HLTciB4aBaXRoodZ4

###

POST http://localhost:3000/api/books
Content-Type: application/json

{
    "title": "The Lord of the Rings: Return of the King",
    "author": "J.R.R. Tolkien",
    "year": 954,
    "edition": 2
}


###Patch
PATCH http://localhost:3000/api/books/662dc8a41e49a1122a623614
Content-Type: application/json

{
    "title": "The Lord of the Rings: Return of the King",
    "author": "J.R.R. Tolkien",
    "year": 954,
    "edition": 2
}
###BSONError: input must be a 24 character hex string, 12 byte Uint8Array, or an integer

###Delete
DELETE http://localhost:3000/api/books/662dc8a41e49a1122a623614


###Post
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "sajan",
    "email": "sajan23@gmail.com",
    "password": "Sajan@123"
}




###Post
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "sajan23@gmail.com",
    "password": "Sajan@123"
}

###update
PUT  http://localhost:3000/api/auth/update
Content-Type: application/json

{
    "username": "sajan",
    "email": "sajan@gmail.com",
    "password": "Sajan@1234",
    "role": "admin"

}
