GET http://localhost:5000/api/books

###

POST http://localhost:5000/api/books
Content-Type: application/json

{
    "title": "The Lord of the Rings",
    "author": "J.R.R. Tolkien",
    "year": 1954
}
